### ISSUE TITLE
[SOK]No OpKernel was registered to support Op 'PreprocessingForward'

### ISSUE THREAD

**Issue by kangna-qi** [DeepRec-AI/DeepRec#804]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04):
- DeepRec version or commit id:5008ddd764137be5a5cc31a3d0e20da7946735c5
- Python version:3.8
- Bazel version (if compiling from source):0.26.1
- GCC/Compiler version (if compiling from source):gcc version 9.4.0
- CUDA/cuDNN version:11.6

**Describe the problem**
I complied the sok according to readme , but run test failed
**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
cd addons/sparse_operation_kit/python
horovodrun -np 2 python embedding_var_lookup_utest.py
```
**Any other info / logs**
```
2023-04-11 15:04:16.434798: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,0]<stderr>:2023-04-11 15:04:17.680362: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,1]<stderr>:2023-04-11 15:04:17.680447: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,0]<stdout>:[INFO]: sparse_operation_kit is imported
[1,1]<stdout>:[INFO]: sparse_operation_kit is imported
[1,0]<stdout>:[SOK INFO] Import /usr/local/lib/python3.8/dist-packages/merlin_sok-1.1.4-py3.8-linux-x86_64.egg/sparse_operation_kit/lib/libsok_experiment.so
[1,1]<stdout>:[SOK INFO] Import /usr/local/lib/python3.8/dist-packages/merlin_sok-1.1.4-py3.8-linux-x86_64.egg/sparse_operation_kit/lib/libsok_experiment.so
[1,1]<stderr>:2023-04-11 15:04:18.916468: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
[1,0]<stderr>:2023-04-11 15:04:18.918099: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100000000 Hz
[1,1]<stderr>:2023-04-11 15:04:18.926324: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5029060 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[1,1]<stderr>:2023-04-11 15:04:18.926375: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[1,0]<stderr>:2023-04-11 15:04:18.927599: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x51f3410 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[1,0]<stderr>:2023-04-11 15:04:18.927635: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[1,1]<stderr>:2023-04-11 15:04:18.928055: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/lib/x86_64-linux-gnu/
[1,1]<stderr>:2023-04-11 15:04:18.928080: E tensorflow/stream_executor/cuda/cuda_driver.cc:282] failed call to cuInit: UNKNOWN ERROR (303)
[1,1]<stderr>:2023-04-11 15:04:18.928111: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: ybjjgu008
[1,1]<stderr>:2023-04-11 15:04:18.928117: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: ybjjgu008
[1,1]<stderr>:2023-04-11 15:04:18.928155: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
[1,1]<stderr>:2023-04-11 15:04:18.928191: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 510.85.2
[1,0]<stderr>:2023-04-11 15:04:18.929274: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short; LD_LIBRARY_PATH: /usr/local/openmpi/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/lib/x86_64-linux-gnu/
[1,0]<stderr>:2023-04-11 15:04:18.929301: E tensorflow/stream_executor/cuda/cuda_driver.cc:282] failed call to cuInit: UNKNOWN ERROR (303)
[1,0]<stderr>:2023-04-11 15:04:18.929330: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: ybjjgu008
[1,0]<stderr>:2023-04-11 15:04:18.929337: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: ybjjgu008
[1,0]<stderr>:2023-04-11 15:04:18.929367: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
[1,0]<stderr>:2023-04-11 15:04:18.929400: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 510.85.2
[1,1]<stdout>:[SOK INFO] Initialize finished, communication tool: horovod
[1,0]<stdout>:[SOK INFO] Initialize finished, communication tool: horovod
[1,1]<stderr>:2023-04-11 15:04:20.239617: W tensorflow/c/c_api.cc:326] Operation '{name:'var_1/Assign' id:22 op device:{} def:{{{node var_1/Assign}} = InitializeKvVariableOp[Tkeys=DT_INT64, _class=["loc:@var_1"], block_num=1, counter_type=DT_UINT64, default_value_dim=1, default_value_no_permission=0, dtype=DT_FLOAT, emb_index=0, false_positive_probability=-1, filter_freq=0, ht_partition_num=1000, ht_type="", initial_num_buckets=131072, l2_weight_threshold=-1, layout="", max_element_size=0, max_freq=99999, max_load_factor=0.8, record_freq=false, record_version=false, shape=[4], slot_index=0, slot_num=1, steps_to_live=0, storage_path=".", storage_size=[1073741824, 1073741824, 1073741824, 1073741824], storage_type=0](var_1, var_1, var_1/Initializer/Const, var_1/Assign/Const)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
[1,0]<stderr>:2023-04-11 15:04:20.251171: W tensorflow/c/c_api.cc:326] Operation '{name:'var_1/Assign' id:22 op device:{} def:{{{node var_1/Assign}} = InitializeKvVariableOp[Tkeys=DT_INT64, _class=["loc:@var_1"], block_num=1, counter_type=DT_UINT64, default_value_dim=1, default_value_no_permission=0, dtype=DT_FLOAT, emb_index=0, false_positive_probability=-1, filter_freq=0, ht_partition_num=1000, ht_type="", initial_num_buckets=131072, l2_weight_threshold=-1, layout="", max_element_size=0, max_freq=99999, max_load_factor=0.8, record_freq=false, record_version=false, shape=[4], slot_index=0, slot_num=1, steps_to_live=0, storage_path=".", storage_size=[1073741824, 1073741824, 1073741824, 1073741824], storage_type=0](var_1, var_1, var_1/Initializer/Const, var_1/Assign/Const)}}' was changed by setting attribute after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
[1,1]<stderr>:    return fn(*args)
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1348, in _run_fn
[1,1]<stderr>:    self._extend_graph()
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1388, in _extend_graph
[1,1]<stderr>:    tf_session.ExtendSession(self._session)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'PreprocessingForward' used by {{node PreprocessingForward/PreprocessingForward}}with these attrs: [id_in_local_rank=0, rank=1, num_ranks=2, Toffsets=DT_INT64, num_gpus=2, Tindices=DT_INT64, num_lookups=2, combiners=["sum", "sum"], dimensions=[128, 4], shard=[-1, -1]]
[1,1]<stderr>:Registered devices: [CPU, XLA_CPU]
[1,1]<stderr>:Registered kernels:
[1,1]<stderr>:  device='GPU'; Tindices in [DT_INT32]; Toffsets in [DT_INT32]
[1,1]<stderr>:  device='GPU'; Tindices in [DT_INT32]; Toffsets in [DT_INT64]
[1,1]<stderr>:  device='GPU'; Tindices in [DT_INT64]; Toffsets in [DT_INT32]
[1,1]<stderr>:  device='GPU'; Tindices in [DT_INT64]; Toffsets in [DT_INT64]
[1,1]<stderr>:
[1,1]<stderr>:	 [[PreprocessingForward/PreprocessingForward]]
[1,1]<stderr>:
[1,1]<stderr>:During handling of the above exception, another exception occurred:
[1,1]<stderr>:
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "embedding_var_lookup_utest.py", line 112, in <module>
[1,1]<stderr>:    loss, embeddings, grads = sess.run(step(sok_vars),feed_dict = {offsets[0]:tmp_offset_numpy[0],offsets[1]:tmp_offset_numpy[1],
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 955, in run
[1,1]<stderr>:    result = self._run(None, fetches, feed_dict, options_ptr,
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1179, in _run
[1,1]<stderr>:    results = self._do_run(handle, final_targets, final_fetches,
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1358, in _do_run
[1,1]<stderr>:    return self._do_call(_run_fn, feeds, fetches, targets, options,
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
[1,1]<stderr>:    raise type(e)(node_def, op, message)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'PreprocessingForward' used by node PreprocessingForward/PreprocessingForward (defined at /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [id_in_local_rank=0, rank=1, num_ranks=2, Toffsets=DT_INT64, num_gpus=2, Tindices=DT_INT64, num_lookups=2, combiners=["sum", "sum"], dimensions=[128, 4], shard=[-1, -1]]
[1,1]<stderr>:Registered devices: [CPU, XLA_CPU]
[1,1]<stderr>:Registered kernels:
[1,1]<stderr>:  device='GPU'; Tindices in [DT_INT32]; Toffsets in [DT_INT32]
[1,1]<stderr>:  device='GPU'; Tindices in [DT_INT32]; Toffsets in [DT_INT64]
[1,1]<stderr>:  device='GPU'; Tindices in [DT_INT64]; Toffsets in [DT_INT32]
[1,1]<stderr>:  device='GPU'; Tindices in [DT_INT64]; Toffsets in [DT_INT64]
[1,1]<stderr>:
[1,1]<stderr>:	 [[PreprocessingForward/PreprocessingForward]]
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
[1,0]<stderr>:    return fn(*args)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1348, in _run_fn
[1,0]<stderr>:    self._extend_graph()
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1388, in _extend_graph
[1,0]<stderr>:    tf_session.ExtendSession(self._session)
[1,0]<stderr>:tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'PreprocessingForward' used by {{node PreprocessingForward/PreprocessingForward}}with these attrs: [num_ranks=2, num_gpus=2, Toffsets=DT_INT64, Tindices=DT_INT64, num_lookups=2, combiners=["sum", "sum"], dimensions=[128, 4], shard=[-1, -1], rank=0, id_in_local_rank=0]
[1,0]<stderr>:Registered devices: [CPU, XLA_CPU]
[1,0]<stderr>:Registered kernels:
[1,0]<stderr>:  device='GPU'; Tindices in [DT_INT32]; Toffsets in [DT_INT32]
[1,0]<stderr>:  device='GPU'; Tindices in [DT_INT32]; Toffsets in [DT_INT64]
[1,0]<stderr>:  device='GPU'; Tindices in [DT_INT64]; Toffsets in [DT_INT32]
[1,0]<stderr>:  device='GPU'; Tindices in [DT_INT64]; Toffsets in [DT_INT64]
[1,0]<stderr>:
[1,0]<stderr>:	 [[PreprocessingForward/PreprocessingForward]]
[1,0]<stderr>:
[1,0]<stderr>:During handling of the above exception, another exception occurred:
[1,0]<stderr>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "embedding_var_lookup_utest.py", line 112, in <module>
[1,0]<stderr>:    loss, embeddings, grads = sess.run(step(sok_vars),feed_dict = {offsets[0]:tmp_offset_numpy[0],offsets[1]:tmp_offset_numpy[1],
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 955, in run
[1,0]<stderr>:    result = self._run(None, fetches, feed_dict, options_ptr,
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1179, in _run
[1,0]<stderr>:    results = self._do_run(handle, final_targets, final_fetches,
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1358, in _do_run
[1,0]<stderr>:    return self._do_call(_run_fn, feeds, fetches, targets, options,
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
[1,0]<stderr>:    raise type(e)(node_def, op, message)
[1,0]<stderr>:tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'PreprocessingForward' used by node PreprocessingForward/PreprocessingForward (defined at /usr/local/lib/python3.8/dist-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [num_ranks=2, num_gpus=2, Toffsets=DT_INT64, Tindices=DT_INT64, num_lookups=2, combiners=["sum", "sum"], dimensions=[128, 4], shard=[-1, -1], rank=0, id_in_local_rank=0]
[1,0]<stderr>:Registered devices: [CPU, XLA_CPU]
[1,0]<stderr>:Registered kernels:
[1,0]<stderr>:  device='GPU'; Tindices in [DT_INT32]; Toffsets in [DT_INT32]
[1,0]<stderr>:  device='GPU'; Tindices in [DT_INT32]; Toffsets in [DT_INT64]
[1,0]<stderr>:  device='GPU'; Tindices in [DT_INT64]; Toffsets in [DT_INT32]
[1,0]<stderr>:  device='GPU'; Tindices in [DT_INT64]; Toffsets in [DT_INT64]
[1,0]<stderr>:
[1,0]<stderr>:	 [[PreprocessingForward/PreprocessingForward]]
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[21763,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```
Include any logs or source code that would be helpful to diagnose the problem.

**Comment by Mesilenceki** [comment]
it seems that your tensorflow package was not compiled with GPU

**Comment by Mesilenceki** [comment]
I am sure that the docker image works. Probably you could check if the nvidia docker is installed on you machine?

**Comment by kangna-qi** [comment]
I  found that the size of libcuda is 0.
```
root@ybjjgu008:/# ll /usr/lib/x86_64-linux-gnu/libcuda*
lrwxrwxrwx 1 root root 12 Dec 26 20:48 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root 21 Dec 26 20:48 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.510.108.03
-rwxr-xr-x 1 root root  0 Dec 26 20:48 /usr/lib/x86_64-linux-gnu/libcuda.so.470.82.01*
-rw-r--r-- 1 root root  0 Dec 26 20:48 /usr/lib/x86_64-linux-gnu/libcuda.so.510.108.03
```
After reinstalling cuda,I solved it.I try to run other release docker and they have the same problem.I really wonder if there is something wrong with docker.@[Mesilenceki](https://github.com/Mesilenceki)
```
root@ybjjgu008:/# ll /usr/lib/x86_64-linux-gnu/libcuda*
lrwxrwxrwx 1 root root       12 Feb 22 20:12 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       20 Feb 22 20:12 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.530.30.02
-rwxr-xr-x 1 root root        0 Dec 26 20:48 /usr/lib/x86_64-linux-gnu/libcuda.so.470.82.01*
-rw-r--r-- 1 root root        0 Dec 26 20:48 /usr/lib/x86_64-linux-gnu/libcuda.so.510.108.03
-rw-r--r-- 1 root root 29900840 Feb 22 12:11 /usr/lib/x86_64-linux-gnu/libcuda.so.530.30.02
lrwxrwxrwx 1 root root       28 Feb 22 20:12 /usr/lib/x86_64-linux-gnu/libcudadebugger.so.1 -> libcudadebugger.so.530.30.02
-rw-r--r-- 1 root root 10488936 Feb 16 09:01 /usr/lib/x86_64-linux-gnu/libcudadebugger.so.530.30.02
```

**Comment by kangna-qi** [comment]
Thanks for your reply. @Mesilenceki @liutongxuan
I used docker instead of nvidia-docker, which caused this problem.nvidia-docker is OK
